version: "3.8"

services:
  app:
    build: .
    container_name: short-url-service
    ports:
      - "8000:8000"
    environment:
      DB_SCHEMA: shorturl
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Dev123456
      DB_POET: 3306  # Typo in your code, should be DB_PORT
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      # REDIS_PASSWORD: ""  # Uncomment if you set a Redis password
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Dev123456
      MYSQL_DATABASE: shorturl
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
